name: "Movies"
description: "Integrating movies-web into home assistant"
version: "4.5.0"
slug: "movies-web"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
